trigger:
  - none

pool:
  vmImage: windows-latest

resources:
  repositories:
    - repository: IaC
      type: git
      name: Melsoft365Platform/IaC

variables:
  - group: apimcicd-variable-group
  - template: environment_setup/provisioning/iac-variables-template.yml@IaC
    parameters:
      envCode: apim

steps:
  - checkout: self
    persistCredentials: true

  - pwsh: |
      git config --global user.email "you@example.com"
      git config --global user.name "$(Build.DefinitionName)"
      git switch -c $(Build.DefinitionName)/$(Build.BuildId)
    workingDirectory: $(Build.SourcesDirectory)/APIManagement
    displayName: Prepare Git

  - task: AzureCLI@2
    displayName: Extract ARM templates
    inputs:
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: pscore
      scriptLocation: inlineScript
      workingDirectory: $(Build.SourcesDirectory)/APIManagement
      inlineScript: >
        ./reskit0.7/apimtemplate extract 
        --extractorConfig ./config/extractSettings.json 
        --resourceGroup $(RG) 
        --sourceApimName $(APIM) 

  - pwsh: |
      git add --all 
      git commit -m "Pipeline: $(Build.DefinitionName) BuildId: $(Build.BuildId) - APIM templates updated"
      git push origin $(Build.DefinitionName)/$(Build.BuildId)
    workingDirectory: $(Build.SourcesDirectory)/APIManagement
    displayName: Push ARM templates

  - task: AzureCLI@2
    displayName: Create PR
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    inputs:
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      workingDirectory: $(Build.SourcesDirectory)/APIManagement
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az repos pr create --org "https://dev.azure.com/Melsoft365DevOps/" --project "Melsoft365Platform" --repository "APIManagement" --source-branch $(Build.DefinitionName)/$(Build.BuildId) --title "APIM ARM templates updated" --description "Created from Pipeline: $(Build.DefinitionName) BuildId: $(Build.BuildId)" --auto-complete true --delete-source-branch true --squash true

  - checkout: self
    clean: true
